### ISSUE TITLE
Large image files

### ISSUE THREAD

**Issue by webb04** [guardian/football-assets#31]
We might be able to improve performance by updating some of the larger files:

![Screenshot 2019-03-29 at 12 16 53](https://user-images.githubusercontent.com/11618797/55232464-904ceb00-521d-11e9-90ff-e3a91d5eff72.png)

**Comment by paperboyo** [comment]
These are source files, @webb04, apps are correctly using them through our fastly resizer. Dotcom should be doing the same, but instead is using resized versions created by the grunt task in this repo, eg. https://sport.guim.co.uk/football/crests/120/1006.png. They are already optimised. Maybe they could be smaller (not sure if they go through pngquant), but I would rather fix dotcom to request them through the resizer and get rid of the sizing/optimisation done here.

And then, I would move the whole shebang (source files) to Tag Manager and kill this whole thing.

Safe to close?
